import type { Metadata } from "next";
import { Geist, Geist_Mono, Pixelify_Sans, Inter } from "next/font/google";
import "./globals.css";
import Themeprovider from "./Themeprovider";
import {
  ClerkProvider,
} from "@clerk/nextjs";
import { Toaster } from "sonner";
import { TooltipProvider } from "@/components/ui/tooltip"; // ✅ Correct import

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const Gamefont = Pixelify_Sans({
  subsets: ["latin"],
  variable: "--font-game",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning className="dark">
        <body
          className={`${geistSans.variable} ${geistMono.variable} 
          ${Gamefont.variable} ${inter.variable} antialiased`}
        >
          <Themeprovider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <TooltipProvider> 
              {children}
              <Toaster />
            </TooltipProvider>
          </Themeprovider>
        </body>
      </html>
    </ClerkProvider>
  );
}
